"""Add enhanced user profile fields

Revision ID: 4a71377b4fc5
Revises: 3976dc10a41d
Create Date: 2025-08-02 12:24:32.311392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a71377b4fc5'
down_revision = '3976dc10a41d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('twitter_handle', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('profile_public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_email', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('show_email')
        batch_op.drop_column('profile_public')
        batch_op.drop_column('github_url')
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('twitter_handle')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('is_active')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('website')
        batch_op.drop_column('location')
        batch_op.drop_column('bio')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
